// os-catalog.js
// Add your own ISO URLs here — point to your cloud server or official mirrors

export const catalog = [
  // ── WINDOWS ──────────────────────────────────────────────────────────────
  {
    id: 'win11',
    name: 'Windows 11',
    version: '23H2',
    category: 'windows',
    arch: '64-bit',
    size: '5.4 GB',
    sizeBytes: 5800000000,
    description: 'The latest Windows with a redesigned Start menu, Snap layouts, and Teams integration.',
    color: '#0078d4',
    icon: 'windows',
    badge: 'latest',
    downloadUrl: 'YOUR_URL_HERE/windows11.iso',
    filename: 'windows11-23H2.iso',
  },
  {
    id: 'win10',
    name: 'Windows 10',
    version: '22H2 LTSC',
    category: 'windows',
    arch: '64-bit',
    size: '4.7 GB',
    sizeBytes: 5050000000,
    description: 'Stable and widely supported. The LTS channel for long-term reliability.',
    color: '#0078d4',
    icon: 'windows',
    badge: 'lts',
    downloadUrl: 'YOUR_URL_HERE/windows10.iso',
    filename: 'windows10-22H2.iso',
  },
  {
    id: 'win7',
    name: 'Windows 7',
    version: 'SP1 Ultimate',
    category: 'windows',
    arch: '64-bit',
    size: '3.2 GB',
    sizeBytes: 3400000000,
    description: 'Classic and beloved. For legacy hardware or compatibility needs.',
    color: '#0078d4',
    icon: 'windows',
    badge: 'legacy',
    downloadUrl: 'YOUR_URL_HERE/windows7.iso',
    filename: 'windows7-SP1.iso',
  },
  {
    id: 'winxp',
    name: 'Windows XP',
    version: 'SP3 Pro',
    category: 'windows',
    arch: '32-bit',
    size: '700 MB',
    sizeBytes: 750000000,
    description: 'The legendary OS. For retro setups, very old hardware, or nostalgia.',
    color: '#0078d4',
    icon: 'windows',
    badge: 'legacy',
    downloadUrl: 'YOUR_URL_HERE/windowsxp.iso',
    filename: 'windowsxp-SP3.iso',
  },

  // ── UBUNTU ───────────────────────────────────────────────────────────────
  {
    id: 'ubuntu2404',
    name: 'Ubuntu',
    version: '24.04 LTS',
    category: 'linux',
    arch: '64-bit',
    size: '2.1 GB',
    sizeBytes: 2260000000,
    description: 'The most popular Linux distro. Great for beginners and pros alike.',
    color: '#e95420',
    icon: 'ubuntu',
    badge: 'lts',
    downloadUrl: 'https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso',
    filename: 'ubuntu-24.04-desktop.iso',
  },
  {
    id: 'ubuntu2204',
    name: 'Ubuntu',
    version: '22.04 LTS',
    category: 'linux',
    arch: '64-bit',
    size: '2.0 GB',
    sizeBytes: 2150000000,
    description: 'Rock-solid LTS release with 5 years of security updates.',
    color: '#e95420',
    icon: 'ubuntu',
    badge: 'stable',
    downloadUrl: 'https://releases.ubuntu.com/22.04/ubuntu-22.04.4-desktop-amd64.iso',
    filename: 'ubuntu-22.04-desktop.iso',
  },

  // ── DEBIAN ───────────────────────────────────────────────────────────────
  {
    id: 'debian12',
    name: 'Debian',
    version: '12 Bookworm',
    category: 'linux',
    arch: '64-bit',
    size: '1.4 GB',
    sizeBytes: 1500000000,
    description: 'The universal OS. Stable, reliable, and the base for many other distros.',
    color: '#a80030',
    icon: 'debian',
    badge: 'stable',
    downloadUrl: 'https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso',
    filename: 'debian-12-netinst.iso',
  },

  // ── LINUX MINT ───────────────────────────────────────────────────────────
  {
    id: 'mint21',
    name: 'Linux Mint',
    version: '21.3 Cinnamon',
    category: 'linux',
    arch: '64-bit',
    size: '2.2 GB',
    sizeBytes: 2360000000,
    description: "Elegant, comfortable, and familiar. The best Linux for Windows switchers.",
    color: '#87cf3e',
    icon: 'mint',
    badge: 'stable',
    downloadUrl: 'YOUR_URL_HERE/linuxmint-21.3.iso',
    filename: 'linuxmint-21.3-cinnamon.iso',
  },

  // ── FEDORA ───────────────────────────────────────────────────────────────
  {
    id: 'fedora40',
    name: 'Fedora',
    version: '40 Workstation',
    category: 'linux',
    arch: '64-bit',
    size: '2.3 GB',
    sizeBytes: 2470000000,
    description: 'Cutting-edge Linux with GNOME 46. Red Hat backed, community driven.',
    color: '#294172',
    icon: 'fedora',
    badge: 'latest',
    downloadUrl: 'https://download.fedoraproject.org/pub/fedora/linux/releases/40/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-40-1.14.iso',
    filename: 'fedora-40-workstation.iso',
  },

  // ── ARCH LINUX ───────────────────────────────────────────────────────────
  {
    id: 'arch',
    name: 'Arch Linux',
    version: '2024.05',
    category: 'linux',
    arch: '64-bit',
    size: '900 MB',
    sizeBytes: 970000000,
    description: "Rolling release, minimal base. You build it your way. Not for beginners.",
    color: '#1793d1',
    icon: 'arch',
    badge: 'rolling',
    downloadUrl: 'https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso',
    filename: 'archlinux-2024.iso',
  },

  // ── KALI LINUX ───────────────────────────────────────────────────────────
  {
    id: 'kali',
    name: 'Kali Linux',
    version: '2024.2',
    category: 'linux',
    arch: '64-bit',
    size: '3.9 GB',
    sizeBytes: 4190000000,
    description: 'Penetration testing and ethical hacking. 600+ security tools pre-installed.',
    color: '#367bf0',
    icon: 'kali',
    badge: 'security',
    downloadUrl: 'YOUR_URL_HERE/kali-linux-2024.2.iso',
    filename: 'kali-linux-2024.2.iso',
  },

  // ── POP!_OS ──────────────────────────────────────────────────────────────
  {
    id: 'popos',
    name: 'Pop!_OS',
    version: '22.04 LTS',
    category: 'linux',
    arch: '64-bit',
    size: '2.5 GB',
    sizeBytes: 2680000000,
    description: 'Made by System76. Tiling window manager, great GPU support, dev-focused.',
    color: '#48b9c7',
    icon: 'pop',
    badge: 'lts',
    downloadUrl: 'YOUR_URL_HERE/pop-os-22.04.iso',
    filename: 'pop-os-22.04.iso',
  },

  // ── MANJARO ──────────────────────────────────────────────────────────────
  {
    id: 'manjaro',
    name: 'Manjaro',
    version: '24.0 Wynsdey',
    category: 'linux',
    arch: '64-bit',
    size: '2.8 GB',
    sizeBytes: 3010000000,
    description: 'Arch-based but user-friendly. Rolling release with a polished GNOME desktop.',
    color: '#35bf5c',
    icon: 'manjaro',
    badge: 'rolling',
    downloadUrl: 'YOUR_URL_HERE/manjaro-24.0.iso',
    filename: 'manjaro-24.0.iso',
  },

  // ── ELEMENTARY OS ────────────────────────────────────────────────────────
  {
    id: 'elementary',
    name: 'elementary OS',
    version: '7.1 Horus',
    category: 'linux',
    arch: '64-bit',
    size: '2.0 GB',
    sizeBytes: 2150000000,
    description: 'The most beautiful Linux distro. macOS-like design, privacy-focused.',
    color: '#64baff',
    icon: 'elementary',
    badge: 'stable',
    downloadUrl: 'YOUR_URL_HERE/elementary-7.1.iso',
    filename: 'elementary-7.1.iso',
  },
]

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'windows', label: 'Windows' },
  { id: 'linux', label: 'Linux' },
]

export const badgeColors = {
  latest:   { bg: '#1a1530', text: '#a78bfa' },
  lts:      { bg: '#0a1e35', text: '#60a5fa' },
  stable:   { bg: '#0e2e1a', text: '#4ade80' },
  rolling:  { bg: '#1a2010', text: '#86efac' },
  legacy:   { bg: '#2a1f10', text: '#fbbf24' },
  security: { bg: '#1a1020', text: '#f472b6' },
}
